application: mapreduce-demo
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /static
  static_dir: static
- url: .*
  script: main.app

includes:
- lib/mapreduce/include.yaml

libraries:
- name: ssl
  version: latest
